### ISSUE TITLE
Please move to a proper maven repository for distribution

### ISSUE THREAD

**Issue by tdekoning** [wingify/vwo-android#12]
Github is not a distribution network for maven/gradle dependencies. Downloading the VWO android sdk is taking up most of our build time, while all other libraries are blazing fast (because they are hosted on a proper maven repository).

Also, because of the hosting on github, gradle decides to download the VWO library every time.

**Comment by matthew-niemann** [comment]
Having the same issue. We have to use Gradle’s “Work offline” option in Android Studio to be able to make any meaningful progress in our development. Please fix!

**Comment by aman400** [comment]
VWO Android SDK is now available via maven central.

```groovy
allprojects {
        repositories {
            ...
            mavenCentral()
            ...
        }
    }
```
```groovy
dependencies {
    ...
    implementation 'com.vwo:mobile:2.4.2@aar'
    ...
}
```
